/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techwheels.Interfaces;

import java.awt.Color;
import techwheels.Clases.Usuario;

/**
 *
 * @author anton
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    private Usuario usuarioLogueado;
    
    public Cliente(){
        initComponents();
        setLocationRelativeTo(this);
    }
    public Cliente(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(this);
          this.usuarioLogueado = usuario;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RealizarCompraBtn = new PanelRound(20);
        RealizarCompraBtnTxt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CancelarCompraBtn = new PanelRound(20);
        CancelarCompraBtnTxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HistorialDeComprasBtn = new PanelRound(20);
        HistorialDeComprasBtnTxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExitBtn = new PanelRound(20);
        ExitBtnTxt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 225, 234));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 400, -1));

        RealizarCompraBtn.setBackground(new java.awt.Color(30, 46, 62));

        RealizarCompraBtnTxt.setBackground(new java.awt.Color(30, 46, 62));
        RealizarCompraBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        RealizarCompraBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        RealizarCompraBtnTxt.setText("   Realizar Compra");
        RealizarCompraBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RealizarCompraBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RealizarCompraBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RealizarCompraBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RealizarCompraBtnLayout = new javax.swing.GroupLayout(RealizarCompraBtn);
        RealizarCompraBtn.setLayout(RealizarCompraBtnLayout);
        RealizarCompraBtnLayout.setHorizontalGroup(
            RealizarCompraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RealizarCompraBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RealizarCompraBtnLayout.setVerticalGroup(
            RealizarCompraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RealizarCompraBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(RealizarCompraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/shopping-cart.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, -1));

        CancelarCompraBtn.setBackground(new java.awt.Color(30, 46, 62));

        CancelarCompraBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        CancelarCompraBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        CancelarCompraBtnTxt.setText("  Cancelar Compra");
        CancelarCompraBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarCompraBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelarCompraBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelarCompraBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CancelarCompraBtnLayout = new javax.swing.GroupLayout(CancelarCompraBtn);
        CancelarCompraBtn.setLayout(CancelarCompraBtnLayout);
        CancelarCompraBtnLayout.setHorizontalGroup(
            CancelarCompraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CancelarCompraBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        CancelarCompraBtnLayout.setVerticalGroup(
            CancelarCompraBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CancelarCompraBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(CancelarCompraBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 140, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/cancelled.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        HistorialDeComprasBtn.setBackground(new java.awt.Color(30, 46, 62));

        HistorialDeComprasBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        HistorialDeComprasBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        HistorialDeComprasBtnTxt.setText("  Historial De Compras");
        HistorialDeComprasBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistorialDeComprasBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HistorialDeComprasBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HistorialDeComprasBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HistorialDeComprasBtnLayout = new javax.swing.GroupLayout(HistorialDeComprasBtn);
        HistorialDeComprasBtn.setLayout(HistorialDeComprasBtnLayout);
        HistorialDeComprasBtnLayout.setHorizontalGroup(
            HistorialDeComprasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistorialDeComprasBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HistorialDeComprasBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HistorialDeComprasBtnLayout.setVerticalGroup(
            HistorialDeComprasBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistorialDeComprasBtnLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(HistorialDeComprasBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(HistorialDeComprasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 170, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/history.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        ExitBtn.setBackground(new java.awt.Color(30, 46, 62));

        ExitBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        ExitBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtnTxt.setText("        SALIR");
        ExitBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitBtnLayout = new javax.swing.GroupLayout(ExitBtn);
        ExitBtn.setLayout(ExitBtnLayout);
        ExitBtnLayout.setHorizontalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExitBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        ExitBtnLayout.setVerticalGroup(
            ExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 140, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/exit.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarCompraBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarCompraBtnTxtMouseEntered
       RealizarCompraBtn.setBackground(new Color(50, 75, 105));
    }//GEN-LAST:event_RealizarCompraBtnTxtMouseEntered

    private void RealizarCompraBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarCompraBtnTxtMouseExited
       RealizarCompraBtn.setBackground(new Color(30, 46, 62));
    }//GEN-LAST:event_RealizarCompraBtnTxtMouseExited

    private void RealizarCompraBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RealizarCompraBtnTxtMouseClicked
       new RealizarCompra(usuarioLogueado).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RealizarCompraBtnTxtMouseClicked

    private void CancelarCompraBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarCompraBtnTxtMouseClicked
       new CancelarCompra().setVisible(true);
          this.dispose();
    }//GEN-LAST:event_CancelarCompraBtnTxtMouseClicked

    private void CancelarCompraBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarCompraBtnTxtMouseEntered
        CancelarCompraBtn.setBackground(new Color(50, 75, 105));
    }//GEN-LAST:event_CancelarCompraBtnTxtMouseEntered

    private void CancelarCompraBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarCompraBtnTxtMouseExited
        CancelarCompraBtn.setBackground(new Color(30, 46, 62));
    }//GEN-LAST:event_CancelarCompraBtnTxtMouseExited

    private void HistorialDeComprasBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialDeComprasBtnTxtMouseClicked
        new HistorialCompra().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_HistorialDeComprasBtnTxtMouseClicked

    private void HistorialDeComprasBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialDeComprasBtnTxtMouseEntered
        HistorialDeComprasBtn.setBackground(new Color(50, 75, 105));
    }//GEN-LAST:event_HistorialDeComprasBtnTxtMouseEntered

    private void HistorialDeComprasBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistorialDeComprasBtnTxtMouseExited
        HistorialDeComprasBtn.setBackground(new Color(30, 46, 62));
    }//GEN-LAST:event_HistorialDeComprasBtnTxtMouseExited

    private void ExitBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnTxtMouseClicked
        new InicioSesion().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_ExitBtnTxtMouseClicked

    private void ExitBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnTxtMouseEntered
        ExitBtn.setBackground(new Color(50, 75, 105));
    }//GEN-LAST:event_ExitBtnTxtMouseEntered

    private void ExitBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnTxtMouseExited
        ExitBtn.setBackground(new Color(30, 46, 62));
    }//GEN-LAST:event_ExitBtnTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CancelarCompraBtn;
    private javax.swing.JLabel CancelarCompraBtnTxt;
    private javax.swing.JPanel ExitBtn;
    private javax.swing.JLabel ExitBtnTxt;
    private javax.swing.JPanel HistorialDeComprasBtn;
    private javax.swing.JLabel HistorialDeComprasBtnTxt;
    private javax.swing.JPanel RealizarCompraBtn;
    private javax.swing.JLabel RealizarCompraBtnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
