/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techwheels.Interfaces;

import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import techwheels.Clases.Enumeraciones.RolUsuarioEnum;
import techwheels.Clases.Usuario;

/**
 *
 * @author anton
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CorreoElecTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LlavesmecanicoImg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EntrarBtn = new javax.swing.JPanel();
        EntrarBtnTxt = new javax.swing.JLabel();
        RegistroBtn = new javax.swing.JPanel();
        RegistroBtnTxt = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JPasswordField();
        chkMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BIENVENIDO USUARIO");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        CorreoElecTxt.setBackground(new java.awt.Color(255, 255, 255));
        CorreoElecTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CorreoElecTxt.setForeground(new java.awt.Color(51, 51, 51));
        CorreoElecTxt.setBorder(null);
        CorreoElecTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        Background.add(CorreoElecTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 25));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 270, 15));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 270, 15));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CONTRASEÑA");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("CORREO ELECTRONICO");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        LlavesmecanicoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/llave-inglesa.png"))); // NOI18N
        LlavesmecanicoImg.setText(" ");
        Background.add(LlavesmecanicoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/cooltext482257288908357.png"))); // NOI18N
        jLabel4.setText("  ");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        EntrarBtn.setBackground(new java.awt.Color(0, 0, 0));

        EntrarBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        EntrarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        EntrarBtnTxt.setText("        ENTRAR");
        EntrarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EntrarBtnLayout = new javax.swing.GroupLayout(EntrarBtn);
        EntrarBtn.setLayout(EntrarBtnLayout);
        EntrarBtnLayout.setHorizontalGroup(
            EntrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EntrarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        EntrarBtnLayout.setVerticalGroup(
            EntrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EntrarBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Background.add(EntrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 40));

        RegistroBtn.setBackground(new java.awt.Color(0, 0, 0));

        RegistroBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        RegistroBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        RegistroBtnTxt.setText("     REGISTRO");
        RegistroBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistroBtnLayout = new javax.swing.GroupLayout(RegistroBtn);
        RegistroBtn.setLayout(RegistroBtnLayout);
        RegistroBtnLayout.setHorizontalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistroBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        RegistroBtnLayout.setVerticalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RegistroBtnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Background.add(RegistroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, 40));

        ContraseñaTxt.setBackground(new java.awt.Color(255, 255, 255));
        ContraseñaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ContraseñaTxt.setBorder(null);
        ContraseñaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTxtActionPerformed(evt);
            }
        });
        Background.add(ContraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, 25));

        chkMostrar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        chkMostrar.setForeground(new java.awt.Color(51, 51, 51));
        chkMostrar.setText("Mostrar contraseña");
        chkMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarActionPerformed(evt);
            }
        });
        Background.add(chkMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseEntered
        EntrarBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_EntrarBtnTxtMouseEntered

    private void EntrarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseExited
        EntrarBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_EntrarBtnTxtMouseExited

    private void RegistroBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseEntered
        RegistroBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_RegistroBtnTxtMouseEntered

    private void RegistroBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseExited
        RegistroBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_RegistroBtnTxtMouseExited

    private void RegistroBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseClicked
        new Registro(). setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroBtnTxtMouseClicked

    private void EntrarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseClicked
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("ConfiguracionBd");
        EntityManager em = emf.createEntityManager();
    try {
        String correo = CorreoElecTxt.getText().trim();
        String contrasena = new String(ContraseñaTxt.getPassword()).trim();
        
        // Validar campos vacíos
        if (correo.isEmpty() || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.");
            return;
        }

        // Buscar usuario por correo y contraseña
        TypedQuery<Usuario> query = em.createQuery(
    "SELECT u FROM Usuarios u WHERE u.correo = :correo AND u.contraseña = :contrasena",
    Usuario.class
);
        query.setParameter("correo", correo);
        query.setParameter("contrasena", contrasena);
        
        Usuario usuario = null;
        try {
            usuario = query.getSingleResult();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
            return;
        }

        // Redirigir según el rol
        if (usuario.getRol() == RolUsuarioEnum.CLIENTE) {
            new Cliente().setVisible(true);
            this.dispose(); // Cierra el JFrame actual
        } else if (usuario.getRol() == RolUsuarioEnum.ADMINISTRADOR) {
            new Administrador().setVisible(true);
            this.dispose(); // Cierra el JFrame actual
        }
        
        JOptionPane.showMessageDialog(this, "Bienvenido, " + usuario.getNombres() + "!");
        
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + ex.getMessage());
    } finally {
        em.close();
        emf.close();
      }  
    }//GEN-LAST:event_EntrarBtnTxtMouseClicked

    private void ContraseñaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTxtActionPerformed

    private void chkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarActionPerformed
        // TODO add your handling code here:
        if (chkMostrar.isSelected()){
            ContraseñaTxt.setEchoChar((char)0);
        }else{
            ContraseñaTxt.setEchoChar('*');
        }
      
    }//GEN-LAST:event_chkMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPasswordField ContraseñaTxt;
    private javax.swing.JTextField CorreoElecTxt;
    private javax.swing.JPanel EntrarBtn;
    private javax.swing.JLabel EntrarBtnTxt;
    private javax.swing.JLabel LlavesmecanicoImg;
    private javax.swing.JPanel RegistroBtn;
    private javax.swing.JLabel RegistroBtnTxt;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
