/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techwheels.Interfaces;

import Controller.UserController;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import techwheels.Clases.Enumeraciones.RolUsuarioEnum;

import techwheels.Clases.Usuario;

/**
 *
 * @author anton
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CorreoElecTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EntrarBtn = new javax.swing.JPanel();
        EntrarBtnTxt = new javax.swing.JLabel();
        RegistroBtn = new javax.swing.JPanel();
        RegistroBtnTxt = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JPasswordField();
        chkMostrar = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 46, 62));
        jLabel1.setText("BIENVENIDO A");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        CorreoElecTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CorreoElecTxt.setForeground(new java.awt.Color(51, 51, 51));
        CorreoElecTxt.setBorder(null);
        Background.add(CorreoElecTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 260, 25));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 270, 15));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 270, 15));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 60, 78));
        jLabel2.setText("CONTRASEÑA");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(46, 60, 78));
        jLabel3.setText("CORREO ELECTRONICO");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        EntrarBtn.setBackground(new java.awt.Color(30, 46, 62));

        EntrarBtnTxt.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        EntrarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        EntrarBtnTxt.setText("        ENTRAR");
        EntrarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout EntrarBtnLayout = new javax.swing.GroupLayout(EntrarBtn);
        EntrarBtn.setLayout(EntrarBtnLayout);
        EntrarBtnLayout.setHorizontalGroup(
            EntrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrarBtnLayout.createSequentialGroup()
                .addComponent(EntrarBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        EntrarBtnLayout.setVerticalGroup(
            EntrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EntrarBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.add(EntrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 40));

        RegistroBtn.setBackground(new java.awt.Color(30, 46, 62));

        RegistroBtnTxt.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        RegistroBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        RegistroBtnTxt.setText("     REGISTRO");
        RegistroBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistroBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistroBtnLayout = new javax.swing.GroupLayout(RegistroBtn);
        RegistroBtn.setLayout(RegistroBtnLayout);
        RegistroBtnLayout.setHorizontalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroBtnLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(RegistroBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        RegistroBtnLayout.setVerticalGroup(
            RegistroBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistroBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RegistroBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Background.add(RegistroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 40));

        ContraseñaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ContraseñaTxt.setBorder(null);
        ContraseñaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTxtActionPerformed(evt);
            }
        });
        Background.add(ContraseñaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 270, 25));

        chkMostrar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        chkMostrar.setForeground(new java.awt.Color(51, 51, 51));
        chkMostrar.setText("Mostrar contraseña");
        chkMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarActionPerformed(evt);
            }
        });
        Background.add(chkMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jPanel1.setBackground(new java.awt.Color(217, 225, 234));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 500, 580));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 46, 62));
        jLabel5.setText("TECHWHEELS");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseEntered
        EntrarBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_EntrarBtnTxtMouseEntered

    private void EntrarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseExited
        EntrarBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_EntrarBtnTxtMouseExited

    private void RegistroBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseEntered
        RegistroBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_RegistroBtnTxtMouseEntered

    private void RegistroBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseExited
        RegistroBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_RegistroBtnTxtMouseExited

    private void RegistroBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistroBtnTxtMouseClicked
        new Registro(). setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RegistroBtnTxtMouseClicked

    private void EntrarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarBtnTxtMouseClicked
       
         String correo = CorreoElecTxt.getText().trim();
         String contraseña = new String(ContraseñaTxt.getPassword()).trim();
         
         
          if (correo.isEmpty() || contraseña.isEmpty()) {
               JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
               return;
             }

    
        UserController controller = new UserController();
        Usuario usuario = controller.login(correo, contraseña);

        if (usuario != null) {
           if (usuario.getRol() == RolUsuarioEnum.ADMINISTRADOR) {
               new Administrador(usuario).setVisible(true);
               this.dispose();
            } else {
              new Cliente(usuario).setVisible(true);
              this.dispose();
            } 
             } else {
                 JOptionPane.showMessageDialog(null, "Correo o contraseña incorrectos");
                     }


    }//GEN-LAST:event_EntrarBtnTxtMouseClicked

    private void ContraseñaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTxtActionPerformed

    private void chkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarActionPerformed
        // TODO add your handling code here:
        if (chkMostrar.isSelected()){
            ContraseñaTxt.setEchoChar((char)0);
        }else{
            ContraseñaTxt.setEchoChar('*');
        }
      
    }//GEN-LAST:event_chkMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPasswordField ContraseñaTxt;
    private javax.swing.JTextField CorreoElecTxt;
    private javax.swing.JPanel EntrarBtn;
    private javax.swing.JLabel EntrarBtnTxt;
    private javax.swing.JPanel RegistroBtn;
    private javax.swing.JLabel RegistroBtnTxt;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
