 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techwheels.Interfaces;

import Controller.InventarioController;
import com.toedter.calendar.JDateChooser;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import techwheels.Clases.CarritoTemp;
import techwheels.Clases.Compra;
import techwheels.Clases.Enumeraciones.GenerarFactura;
import techwheels.Clases.Usuario;
import techwheels.DAO.CarritoDAO;
import techwheels.DAO.CompraDAO;




/**
 *
 * @author anton
 */
public class RealizarCompra extends javax.swing.JFrame {

    /**
     * Creates new form VerArticulos
     */
    private Usuario usuarioActual;
    private Compra compraActual;
   
    private CarritoDAO carritoDAO = new CarritoDAO();
            

    
    public RealizarCompra() {
        initComponents();
        setLocationRelativeTo(this);
       
               
    }
    
     public RealizarCompra(Usuario usuario) {
        initComponents();
        setLocationRelativeTo(this);
        this.usuarioActual = usuario;
        cargarDatosUsuario();
       
        
    }
     
    private void cargarDatosUsuario() {
        textNombre.setText(usuarioActual.getNombres());
        textApellidos.setText(usuarioActual.getApellidos());
        txtTipoDocumento.setText(usuarioActual.getTipoDocumento());
        txtNumeroDocumento.setText(usuarioActual.getNumeroDocumento());
    }
    
     public void cargarProductos() {
        DefaultTableModel product = (DefaultTableModel) TablaProductos.getModel();
        product.setRowCount(0);
        InventarioController inventario = new InventarioController();
        inventario.cargarProductos(product);

    }
    
     private void mostrarCalendario() {
     JDateChooser datechooser = new JDateChooser();
     datechooser.setDateFormatString("dd/MM/yyyy");
     
     int opcion = JOptionPane.showConfirmDialog(
         this,
         datechooser,
         "Seleccione una fecha",
         JOptionPane.OK_CANCEL_OPTION,
         JOptionPane.PLAIN_MESSAGE
     
     
     );
     
     if(opcion == JOptionPane.OK_OPTION){
         Date fechaseleccionada = datechooser.getDate();
         if(fechaseleccionada !=null){
             SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
             txtFecha.setText(formato.format(fechaseleccionada));
         }else{
            JOptionPane.showMessageDialog(this, "No seleccionaste nisnguna fecha");
         }
             
     }
        
    } 
    
    private void mostrarCarrito() {
    List<CarritoTemp> carrito = carritoDAO.listarcarrito();
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[]{"Nombre", "Descripción", "Marca", "Categoría", "Precio", "Cantidad"}, 0
    );

    for (CarritoTemp c : carrito) {
        modelo.addRow(new Object[]{
            c.getNombreProducto(),
            c.getDescripcionProducto(),
            c.getMarcaProducto(),
            c.getCategoriaProducto(),
            c.getPrecioProducto(),
            c.getCantidad()
        });
    }

    TablaProductos.setModel(modelo);
}
     
    
    
    /*public void setImagenEnLabel(JLabel label, String rutaImagen) {
    ImageIcon icon = new ImageIcon(rutaImagen);
    Image img = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
    label.setIcon(new ImageIcon(img));
}*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btnQuitar = new PanelRound(20);
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnVerCarrito = new PanelRound(20);
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAgregar = new PanelRound(20);
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTipoDocumento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnFecha = new javax.swing.JButton();
        btnRealizarCompra = new PanelRound(20);
        jLabel12 = new javax.swing.JLabel();
        btnDescargarFactura = new PanelRound(20);
        jLabel13 = new javax.swing.JLabel();
        btnCargarProductos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ComboMetodoPago = new javax.swing.JComboBox<>();
        spinnerCantidad = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(247, 250, 252));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        TablaProductos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Marca", "Categoria", "Precio", "Disponible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaProductos.setName(""); // NOI18N
        jScrollPane1.setViewportView(TablaProductos);

        PanelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 117, 680, 509));

        btnQuitar.setBackground(new java.awt.Color(192, 221, 245));
        btnQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuitarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Quitar del carrito");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/cancelled.png"))); // NOI18N

        javax.swing.GroupLayout btnQuitarLayout = new javax.swing.GroupLayout(btnQuitar);
        btnQuitar.setLayout(btnQuitarLayout);
        btnQuitarLayout.setHorizontalGroup(
            btnQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQuitarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        btnQuitarLayout.setVerticalGroup(
            btnQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnQuitarLayout.createSequentialGroup()
                .addGroup(btnQuitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnQuitarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnQuitarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPrincipal.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, -1, -1));

        btnVerCarrito.setBackground(new java.awt.Color(192, 221, 245));
        btnVerCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerCarritoMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Ver carrito");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/shopping-cart.png"))); // NOI18N

        javax.swing.GroupLayout btnVerCarritoLayout = new javax.swing.GroupLayout(btnVerCarrito);
        btnVerCarrito.setLayout(btnVerCarritoLayout);
        btnVerCarritoLayout.setHorizontalGroup(
            btnVerCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerCarritoLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );
        btnVerCarritoLayout.setVerticalGroup(
            btnVerCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVerCarritoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnVerCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18))
                .addGap(15, 15, 15))
        );

        PanelPrincipal.add(btnVerCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 640, 130, -1));

        btnAgregar.setBackground(new java.awt.Color(192, 221, 245));
        btnAgregar.setForeground(new java.awt.Color(0, 120, 215));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Agregar al carrito");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/shopping-cart.png"))); // NOI18N

        javax.swing.GroupLayout btnAgregarLayout = new javax.swing.GroupLayout(btnAgregar);
        btnAgregar.setLayout(btnAgregarLayout);
        btnAgregarLayout.setHorizontalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );
        btnAgregarLayout.setVerticalGroup(
            btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAgregarLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(btnAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnAgregarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14))))
        );

        PanelPrincipal.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 640, 170, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel4.setText("TECHWHEELS");
        PanelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(46, 60, 78));
        jLabel5.setText("Apellidos");
        PanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        textNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(textNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        textApellidos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        textApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(textApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 220, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(46, 60, 78));
        jLabel6.setText("Nombre");
        PanelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(46, 60, 78));
        jLabel7.setText("Tipo de Documento");
        PanelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtTipoDocumento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTipoDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(txtTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 60, 78));
        jLabel8.setText("Numero de Documento");
        PanelPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        txtNumeroDocumento.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNumeroDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(txtNumeroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 220, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 60, 78));
        jLabel9.setText("Direccion de Envio");
        PanelPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 480, 40));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 60, 78));
        jLabel10.setText("Metodo de pago");
        PanelPrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 60, 78));
        jLabel11.setText("Fecha");
        PanelPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        PanelPrincipal.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 150, 30));

        btnFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/visibility.png"))); // NOI18N
        btnFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechaActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 50, 30));

        btnRealizarCompra.setBackground(new java.awt.Color(0, 120, 215));
        btnRealizarCompra.setForeground(new java.awt.Color(0, 120, 215));
        btnRealizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRealizarCompraMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Realizar compra");

        javax.swing.GroupLayout btnRealizarCompraLayout = new javax.swing.GroupLayout(btnRealizarCompra);
        btnRealizarCompra.setLayout(btnRealizarCompraLayout);
        btnRealizarCompraLayout.setHorizontalGroup(
            btnRealizarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRealizarCompraLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(58, 58, 58))
        );
        btnRealizarCompraLayout.setVerticalGroup(
            btnRealizarCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRealizarCompraLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        PanelPrincipal.add(btnRealizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 230, 50));

        btnDescargarFactura.setBackground(new java.awt.Color(232, 234, 236));
        btnDescargarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescargarFacturaMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Descargar factura");

        javax.swing.GroupLayout btnDescargarFacturaLayout = new javax.swing.GroupLayout(btnDescargarFactura);
        btnDescargarFactura.setLayout(btnDescargarFacturaLayout);
        btnDescargarFacturaLayout.setHorizontalGroup(
            btnDescargarFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDescargarFacturaLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(43, 43, 43))
        );
        btnDescargarFacturaLayout.setVerticalGroup(
            btnDescargarFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDescargarFacturaLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(14, 14, 14))
        );

        PanelPrincipal.add(btnDescargarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 220, 50));

        btnCargarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarProductosMouseClicked(evt);
            }
        });

        jLabel14.setText("Cargar Productos");

        javax.swing.GroupLayout btnCargarProductosLayout = new javax.swing.GroupLayout(btnCargarProductos);
        btnCargarProductos.setLayout(btnCargarProductosLayout);
        btnCargarProductosLayout.setHorizontalGroup(
            btnCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarProductosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        btnCargarProductosLayout.setVerticalGroup(
            btnCargarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCargarProductosLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        PanelPrincipal.add(btnCargarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 130, 30));

        ComboMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Efectivo", "Contra Entrega", "Tarjeta" }));
        ComboMetodoPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 223, 223)));
        ComboMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMetodoPagoActionPerformed(evt);
            }
        });
        PanelPrincipal.add(ComboMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 190, 30));
        PanelPrincipal.add(spinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 660, 90, 30));

        jLabel15.setText("Cantidad");
        PanelPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 640, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, -1, -1));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1251, 726));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMetodoPagoActionPerformed

    private void btnCargarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarProductosMouseClicked
        cargarProductos();
// TODO add your handling code here:
    }//GEN-LAST:event_btnCargarProductosMouseClicked

    private void btnFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechaActionPerformed
       mostrarCalendario();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFechaActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
   int fila =  TablaProductos.getSelectedRow();
   if (fila != -1) {
        String nombre = TablaProductos.getValueAt(fila, 0).toString();
        String descripcion = TablaProductos.getValueAt(fila, 1).toString();
        String marca = TablaProductos.getValueAt(fila, 2).toString();
        String categoria = TablaProductos.getValueAt(fila, 3).toString();
        double precio = Double.parseDouble(TablaProductos.getValueAt(fila, 4).toString());
        int cantidad = (int)spinnerCantidad.getValue();
        
        

        CarritoTemp item = new CarritoTemp(nombre, descripcion, marca, categoria, precio, cantidad);
        carritoDAO.agregarProductoCarrito(item);

        JOptionPane.showMessageDialog(this, "Producto agregado al carrito");
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un producto");
    }
   

   
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnQuitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitarMouseClicked
    int fila = TablaProductos.getSelectedRow();
    if (fila != -1) {
    String nombre =TablaProductos.getValueAt(fila, 0).toString();
    carritoDAO.eliminarProductoCarrito(nombre);
    JOptionPane.showMessageDialog(this, "Producto eliminado del carrito");
    mostrarCarrito(); // Vuelve a cargar
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarMouseClicked

    private void btnVerCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerCarritoMouseClicked
        mostrarCarrito();
                
// TODO add your handling code here:
    }//GEN-LAST:event_btnVerCarritoMouseClicked

    private void btnRealizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRealizarCompraMouseClicked

    CompraDAO compraDAO = new CompraDAO();
    List<CarritoTemp> carrito = carritoDAO.listarcarrito();
    if (carrito.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El carrito está vacío. Agrega productos antes de realizar la compra.");
        return;
    }
    
    String nombre = textNombre.getText();
    String apellido = textApellidos.getText();
    String tipoDoc = txtTipoDocumento.getText();
    String numeroDoc = txtNumeroDocumento.getText();
    String metodoPago = (String)ComboMetodoPago.getSelectedItem();
    String fecha = txtFecha.getText();
    String direccion = txtDireccion.getText();
    
    double subtotal = 0;
    for (CarritoTemp p : carrito) {
        subtotal += p.getPrecioProducto() * p.getCantidad();
    }
    
    double total = 0.0;
    for (int i = 0; i < TablaProductos.getRowCount(); i++) {
        double precio = Double.parseDouble(TablaProductos.getValueAt(i, 4).toString());
        int cantidad = Integer.parseInt(TablaProductos.getValueAt(i, 5).toString());
        total += precio * cantidad;
    }
    
      if ("Tarjeta".equalsIgnoreCase(metodoPago)) {
        String numeroTarjeta = JOptionPane.showInputDialog(this, "Ingrese el número de tarjeta:");
        if (numeroTarjeta == null || numeroTarjeta.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pago cancelado.");
            return;
        }
        JOptionPane.showMessageDialog(this, "Pago realizado exitosamente con tarjeta terminada en " +
                numeroTarjeta.substring(Math.max(0, numeroTarjeta.length() - 4)) + ".");
    }
      
    Compra compra = new Compra(nombre, apellido, tipoDoc, numeroDoc, metodoPago, carrito, direccion, fecha, subtotal, total);
    compraDAO.guardarCompra(compra);
    compraActual = compra;


    carritoDAO.vaciarCarrito();
    JOptionPane.showMessageDialog(this, "Compra realizada con éxito.\nTotal pagado: $" + compra.getTotal());
     

// TODO add your handling code here:
    }//GEN-LAST:event_btnRealizarCompraMouseClicked

    private void btnDescargarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescargarFacturaMouseClicked
         if (compraActual == null) {
        JOptionPane.showMessageDialog(this, "No hay una compra reciente para generar la factura.");
        return;
    }
    
    GenerarFactura.generarFacturaPDF(compraActual);
    JOptionPane.showMessageDialog(this, "Factura generada correctamente.");

// TODO add your handling code here:
    }//GEN-LAST:event_btnDescargarFacturaMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Cliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMetodoPago;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnCargarProductos;
    private javax.swing.JPanel btnDescargarFactura;
    private javax.swing.JButton btnFecha;
    private javax.swing.JPanel btnQuitar;
    private javax.swing.JPanel btnRealizarCompra;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel btnVerCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
