/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package techwheels.Interfaces;

import Controller.UserController;
import java.awt.Color;
import java.util.List;
import java.util.UUID;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import techwheels.Clases.Enumeraciones.RolUsuarioEnum;

import techwheels.Clases.Usuario;
import techwheels.DAO.UsuarioDAO;

/**
 *
 * @author anton
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(this);
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Background = new javax.swing.JPanel();
        javax.swing.JPanel RoundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        ApellidoTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        CorreoTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        TelefonoTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        ComboDocumento = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        NumeroDocumentoTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        ComboRol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        VolverBtn = new javax.swing.JPanel();
        VolverBtnTxt = new javax.swing.JLabel();
        RegistrarBtn = new javax.swing.JPanel();
        RegistrarBtnTxt = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        Background.setBackground(new java.awt.Color(217, 225, 234));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RoundPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 46, 62));
        jLabel2.setText("REGISTRO");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techwheels/Imagenes/agregar-usuario.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel3.setText("Nombre");

        NombreTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        NombreTxt.setBorder(null);
        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel4.setText("Apellidos");

        ApellidoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ApellidoTxt.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel5.setText("Correo Electronico");

        CorreoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        CorreoTxt.setBorder(null);

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel10.setText("Telefono");

        TelefonoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        TelefonoTxt.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel6.setText("Tipo de Documento");

        ComboDocumento.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ComboDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tarjeta de identidad", "Cedula de Ciudadania", " " }));
        ComboDocumento.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel7.setText("Numero de Documento");

        NumeroDocumentoTxt.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        NumeroDocumentoTxt.setBorder(null);

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel9.setText("Rol");

        ComboRol.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        ComboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cliente", "Administrador" }));
        ComboRol.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jLabel8.setText("Contraseña");

        ContraseñaTxt.setBorder(null);

        VolverBtn.setBackground(new java.awt.Color(0, 0, 0));

        VolverBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        VolverBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        VolverBtnTxt.setText("     VOLVER");
        VolverBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolverBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolverBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout VolverBtnLayout = new javax.swing.GroupLayout(VolverBtn);
        VolverBtn.setLayout(VolverBtnLayout);
        VolverBtnLayout.setHorizontalGroup(
            VolverBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VolverBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(VolverBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        VolverBtnLayout.setVerticalGroup(
            VolverBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VolverBtnLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(VolverBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        RegistrarBtn.setBackground(new java.awt.Color(0, 0, 0));

        RegistrarBtnTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        RegistrarBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        RegistrarBtnTxt.setText(" REGISTRAR");
        RegistrarBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout RegistrarBtnLayout = new javax.swing.GroupLayout(RegistrarBtn);
        RegistrarBtn.setLayout(RegistrarBtnLayout);
        RegistrarBtnLayout.setHorizontalGroup(
            RegistrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrarBtnTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrarBtnLayout.setVerticalGroup(
            RegistrarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarBtnLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(RegistrarBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout RoundPanelLayout = new javax.swing.GroupLayout(RoundPanel);
        RoundPanel.setLayout(RoundPanelLayout);
        RoundPanelLayout.setHorizontalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoundPanelLayout.createSequentialGroup()
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RoundPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RoundPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TelefonoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(CorreoTxt)
                            .addComponent(jLabel5)
                            .addComponent(ApellidoTxt)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(RoundPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(NombreTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(ComboDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(NumeroDocumentoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(jLabel9)
                            .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(ContraseñaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jSeparator5))))
                .addGap(88, 88, 88))
        );
        RoundPanelLayout.setVerticalGroup(
            RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoundPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RoundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addGap(24, 24, 24)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RoundPanelLayout.createSequentialGroup()
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumeroDocumentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RoundPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VolverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Background.add(RoundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 630, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBtnTxtMouseEntered
      VolverBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_VolverBtnTxtMouseEntered

    private void VolverBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBtnTxtMouseExited
      VolverBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_VolverBtnTxtMouseExited

    private void VolverBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverBtnTxtMouseClicked
      new InicioSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverBtnTxtMouseClicked

    private void RegistrarBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBtnTxtMouseEntered
        RegistrarBtn.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_RegistrarBtnTxtMouseEntered

    private void RegistrarBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBtnTxtMouseExited
       RegistrarBtn.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_RegistrarBtnTxtMouseExited

    private void RegistrarBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBtnTxtMouseClicked
      
   try {
        // Validaciones de campos obligatorios
        if (NombreTxt.getText().trim().isEmpty() ||
            ApellidoTxt.getText().trim().isEmpty() ||
            ComboRol.getSelectedItem() == null ||
            NumeroDocumentoTxt.getText().trim().isEmpty() ||
            CorreoTxt.getText().trim().isEmpty() ||
            ContraseñaTxt.getText().trim().isEmpty() ||
            ComboDocumento.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios.");
            return;
        }
        
         // Validaciones de formato
        if (!NombreTxt.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
            JOptionPane.showMessageDialog(null, "El nombre solo debe contener letras.");
            return;
        }
        if (!ApellidoTxt.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+")) {
            JOptionPane.showMessageDialog(null, "El apellido solo debe contener letras.");
            return;
        }
        if (!NumeroDocumentoTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "El número de documento solo debe contener números.");
            return;
        }
        if (CorreoTxt.getText().trim().length() > 100) {
            JOptionPane.showMessageDialog(null, "El correo no puede superar los 100 caracteres.");
            return;
        }
        if (TelefonoTxt.getText().trim().length() > 15) {
            JOptionPane.showMessageDialog(null, "El teléfono no puede superar los 15 caracteres.");
            return;
        }
        if (!TelefonoTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "El teléfono solo debe contener números.");
            return;
        }
        if (ContraseñaTxt.getText().trim().length() > 70) {
            JOptionPane.showMessageDialog(null, "La contraseña no puede superar los 70 caracteres.");
            return;
        }
        if (!CorreoTxt.getText().trim().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(null, "El correo no tiene un formato válido.");
            return;
        }
        
         // Cargar usuarios existentes
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        List<Usuario> usuarios = usuarioDAO.listarUsuarios();

        // Validar unicidad de correo y documento
        for (Usuario u : usuarios) {
            if (u.getCorreo().equalsIgnoreCase(CorreoTxt.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese correo.");
                return;
            }
            if (u.getNumeroDocumento().equalsIgnoreCase(NumeroDocumentoTxt.getText().trim())) {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con ese número de documento.");
                return;
            }
        }
        
         // Crear nuevo usuario
        Usuario usuario = new Usuario();
        usuario.setCodigo(UUID.randomUUID().toString());
        usuario.setNombres(NombreTxt.getText().trim());
        usuario.setApellidos(ApellidoTxt.getText().trim());
        usuario.setTipoDocumento(ComboDocumento.getSelectedItem().toString());
        usuario.setNumeroDocumento(NumeroDocumentoTxt.getText().trim());
        usuario.setCorreo(CorreoTxt.getText().trim());
        usuario.setTelefono(TelefonoTxt.getText().trim());
        usuario.setContraseña(ContraseñaTxt.getText().trim());

        // Convertir string a enum (si lo usas)
        String rolSeleccionado = ComboRol.getSelectedItem().toString().toUpperCase();
        try {
            usuario.setRol(RolUsuarioEnum.valueOf(rolSeleccionado));
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Rol inválido: " + rolSeleccionado);
            return;
        }

        // Agregar y guardar usuario
        usuarios.add(usuario);
        UserController controller = new UserController();
        controller.registrarUsuario(usuario);

        JOptionPane.showMessageDialog(null, "Registro exitoso.");
        limpiarCampos();
        
        } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al registrar: " + e.getMessage());
    }
   

   

    

    }//GEN-LAST:event_RegistrarBtnTxtMouseClicked

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTxt;
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> ComboDocumento;
    private javax.swing.JComboBox<String> ComboRol;
    private javax.swing.JPasswordField ContraseñaTxt;
    private javax.swing.JTextField CorreoTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JTextField NumeroDocumentoTxt;
    private javax.swing.JPanel RegistrarBtn;
    private javax.swing.JLabel RegistrarBtnTxt;
    private javax.swing.JTextField TelefonoTxt;
    private javax.swing.JPanel VolverBtn;
    private javax.swing.JLabel VolverBtnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        NombreTxt.setText("");
    ApellidoTxt.setText("");
    NumeroDocumentoTxt.setText("");
    CorreoTxt.setText("");
    TelefonoTxt.setText("");
    ContraseñaTxt.setText("");
    
    ComboRol.setSelectedIndex(-1);        // Para que no quede nada seleccionado
    ComboDocumento.setSelectedIndex(-1);  // Igual, si quieres que se deseleccione
    }
}
